[package]
name = "fefy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
fef = { version = "0.2.2", features = ["v0"] }
phf = { version = "0.11.3", features = ["macros"] }
